const boards = {
  '8x8': [
    [
      { enabled: false, index: 0 },
      { enabled: false, index: 1 },
      { enabled: false, index: 2 },
      { enabled: false, index: 3 },
      { enabled: false, index: 4 },
      { enabled: true, index: 5 },
      { enabled: false, index: 6 },
      { enabled: false, index: 7 },
    ],
    [
      { enabled: false, index: 8 },
      { enabled: true, index: 9 },
      { enabled: true, index: 10 },
      { enabled: true, index: 11 },
      { enabled: true, index: 12 },
      { enabled: true, index: 13 },
      { enabled: true, index: 14 },
      { enabled: false, index: 15 },
    ],
    [
      { enabled: false, index: 16 },
      { enabled: true, index: 17 },
      { enabled: false, index: 18 },
      { enabled: false, index: 19 },
      { enabled: false, index: 20 },
      { enabled: false, index: 21 },
      { enabled: true, index: 22 },
      { enabled: false, index: 23 },
    ],
    [
      { enabled: false, index: 24 },
      { enabled: true, index: 25 },
      { enabled: false, index: 26 },
      { enabled: true, index: 27 },
      { enabled: false, index: 28 },
      { enabled: true, index: 29 },
      { enabled: true, index: 30 },
      { enabled: false, index: 31 },
    ],
    [
      { enabled: false, index: 32 },
      { enabled: true, index: 33 },
      { enabled: false, index: 34 },
      { enabled: true, index: 35 },
      { enabled: false, index: 36 },
      { enabled: false, index: 37 },
      { enabled: true, index: 38 },
      { enabled: false, index: 39 },
    ],
    [
      { enabled: false, index: 40 },
      { enabled: true, index: 41 },
      { enabled: false, index: 42 },
      { enabled: true, index: 43 },
      { enabled: false, index: 44 },
      { enabled: true, index: 45 },
      { enabled: true, index: 46 },
      { enabled: false, index: 47 },
    ],
    [
      { enabled: false, index: 48 },
      { enabled: true, index: 49 },
      { enabled: true, index: 50 },
      { enabled: true, index: 51 },
      { enabled: true, index: 52 },
      { enabled: true, index: 53 },
      { enabled: true, index: 54 },
      { enabled: false, index: 55 },
    ],
    [
      { enabled: false, index: 56 },
      { enabled: false, index: 57 },
      { enabled: false, index: 58 },
      { enabled: false, index: 59 },
      { enabled: false, index: 60 },
      { enabled: false, index: 61 },
      { enabled: false, index: 62 },
      { enabled: false, index: 63 },
    ],
  ],
  '12x12': [
    [
      { enabled: false, index: 0 },
      { enabled: false, index: 1 },
      { enabled: false, index: 2 },
      { enabled: false, index: 3 },
      { enabled: false, index: 4 },
      { enabled: false, index: 5 },
      { enabled: false, index: 6 },
      { enabled: false, index: 7 },
      { enabled: false, index: 8 },
      { enabled: false, index: 9 },
      { enabled: false, index: 10 },
      { enabled: false, index: 11 },
    ],
    [
      { enabled: false, index: 12 },
      { enabled: true, index: 13 },
      { enabled: true, index: 14 },
      { enabled: true, index: 15 },
      { enabled: true, index: 16 },
      { enabled: false, index: 17 },
      { enabled: true, index: 18 },
      { enabled: true, index: 19 },
      { enabled: true, index: 20 },
      { enabled: false, index: 21 },
      { enabled: true, index: 22 },
      { enabled: false, index: 23 },
    ],
    [
      { enabled: false, index: 24 },
      { enabled: true, index: 25 },
      { enabled: false, index: 26 },
      { enabled: false, index: 27 },
      { enabled: true, index: 28 },
      { enabled: false, index: 29 },
      { enabled: false, index: 30 },
      { enabled: true, index: 31 },
      { enabled: false, index: 32 },
      { enabled: false, index: 33 },
      { enabled: true, index: 34 },
      { enabled: false, index: 35 },
    ],
    [
      { enabled: false, index: 36 },
      { enabled: true, index: 37 },
      { enabled: true, index: 38 },
      { enabled: false, index: 39 },
      { enabled: true, index: 40 },
      { enabled: true, index: 41 },
      { enabled: true, index: 42 },
      { enabled: true, index: 43 },
      { enabled: true, index: 44 },
      { enabled: true, index: 45 },
      { enabled: true, index: 46 },
      { enabled: false, index: 47 },
    ],
    [
      { enabled: false, index: 48 },
      { enabled: true, index: 49 },
      { enabled: false, index: 50 },
      { enabled: false, index: 51 },
      { enabled: false, index: 52 },
      { enabled: false, index: 53 },
      { enabled: false, index: 54 },
      { enabled: false, index: 55 },
      { enabled: false, index: 56 },
      { enabled: false, index: 57 },
      { enabled: true, index: 58 },
      { enabled: false, index: 59 },
    ],
    [
      { enabled: false, index: 60 },
      { enabled: true, index: 61 },
      { enabled: true, index: 62 },
      { enabled: true, index: 63 },
      { enabled: true, index: 64 },
      { enabled: true, index: 65 },
      { enabled: false, index: 66 },
      { enabled: true, index: 67 },
      { enabled: true, index: 68 },
      { enabled: true, index: 69 },
      { enabled: true, index: 70 },
      { enabled: false, index: 71 },
    ],
    [
      { enabled: false, index: 72 },
      { enabled: false, index: 73 },
      { enabled: false, index: 74 },
      { enabled: true, index: 75 },
      { enabled: false, index: 76 },
      { enabled: true, index: 77 },
      { enabled: false, index: 78 },
      { enabled: true, index: 79 },
      { enabled: false, index: 80 },
      { enabled: false, index: 81 },
      { enabled: true, index: 82 },
      { enabled: false, index: 83 },
    ],
    [
      { enabled: false, index: 84 },
      { enabled: true, index: 85 },
      { enabled: true, index: 86 },
      { enabled: true, index: 87 },
      { enabled: false, index: 88 },
      { enabled: true, index: 89 },
      { enabled: true, index: 90 },
      { enabled: true, index: 91 },
      { enabled: false, index: 92 },
      { enabled: true, index: 93 },
      { enabled: true, index: 94 },
      { enabled: false, index: 95 },
    ],
    [
      { enabled: false, index: 96 },
      { enabled: true, index: 97 },
      { enabled: false, index: 98 },
      { enabled: true, index: 99 },
      { enabled: false, index: 100 },
      { enabled: false, index: 101 },
      { enabled: false, index: 102 },
      { enabled: false, index: 103 },
      { enabled: false, index: 104 },
      { enabled: true, index: 105 },
      { enabled: false, index: 106 },
      { enabled: false, index: 107 },
    ],
    [
      { enabled: false, index: 108 },
      { enabled: true, index: 109 },
      { enabled: false, index: 110 },
      { enabled: true, index: 111 },
      { enabled: true, index: 112 },
      { enabled: true, index: 113 },
      { enabled: true, index: 114 },
      { enabled: true, index: 115 },
      { enabled: true, index: 116 },
      { enabled: true, index: 117 },
      { enabled: false, index: 118 },
      { enabled: false, index: 119 },
    ],
    [
      { enabled: false, index: 120 },
      { enabled: true, index: 121 },
      { enabled: false, index: 122 },
      { enabled: false, index: 123 },
      { enabled: false, index: 124 },
      { enabled: false, index: 125 },
      { enabled: true, index: 126 },
      { enabled: false, index: 127 },
      { enabled: false, index: 128 },
      { enabled: true, index: 129 },
      { enabled: true, index: 130 },
      { enabled: false, index: 131 },
    ],
    [
      { enabled: false, index: 132 },
      { enabled: true, index: 133 },
      { enabled: true, index: 134 },
      { enabled: false, index: 135 },
      { enabled: true, index: 136 },
      { enabled: true, index: 137 },
      { enabled: true, index: 138 },
      { enabled: true, index: 139 },
      { enabled: true, index: 140 },
      { enabled: true, index: 141 },
      { enabled: true, index: 142 },
      { enabled: false, index: 143 },
    ],
  ],
}

export default boards;
